.386
.model flat, stdcall
option casemap:none

includelib msvcrt.lib
includelib user32.lib
includelib kernel32.lib

printf PROTO C : ptr sbyte, :VARARG
scanf PROTO C : ptr sbyte, :VARARG

.data
forIntNumber	db '%d',0
forString	db '%s',0
forEnter	db ' ',0
IntNumberHolder dd 0

.code
__init:
	call main
	ret
Mars_PrintInt:
	mov esi, [esp+4]
	pushad
	invoke printf, offset forIntNumber, esi
	invoke printf, offset forEnter
	popad
	ret
Mars_GetInt:
	pushad
	invoke scanf, offset forIntNumber, offset IntNumberHolder
	popad
	lea eax, IntNumberHolder
	mov eax, [eax]
	ret
Mars_PrintStr:
	mov esi, [esp+4]
	pushad
	invoke printf, offset forString, esi
	popad
	ret
main:
	push ebp
	mov ebp, esp
	sub esp, 104
	mov edx, 1
	mov esi, ebp
	add esi, -4
	mov eax, [esi]
	mov eax, edx
	mov esi, ebp
	add esi, -4
	mov [esi], eax
	mov edx, 2
	mov esi, ebp
	add esi, -8
	mov eax, [esi]
	mov eax, edx
	mov esi, ebp
	add esi, -8
	mov [esi], eax
	mov edx, 3
	mov esi, ebp
	add esi, -12
	mov eax, [esi]
	mov eax, edx
	mov esi, ebp
	add esi, -12
	mov [esi], eax
	mov edx, 4
	mov esi, ebp
	add esi, -16
	mov eax, [esi]
	mov eax, edx
	mov esi, ebp
	add esi, -16
	mov [esi], eax
	mov edx, 5
	mov esi, ebp
	add esi, -20
	mov eax, [esi]
	mov eax, edx
	mov esi, ebp
	add esi, -20
	mov [esi], eax
	mov edx, 6
	mov esi, ebp
	add esi, -24
	mov eax, [esi]
	mov eax, edx
	mov esi, ebp
	add esi, -24
	mov [esi], eax
	mov edx, 7
	mov esi, ebp
	add esi, -28
	mov eax, [esi]
	mov eax, edx
	mov esi, ebp
	add esi, -28
	mov [esi], eax
	mov edx, 8
	mov esi, ebp
	add esi, -32
	mov eax, [esi]
	mov eax, edx
	mov esi, ebp
	add esi, -32
	mov [esi], eax
	mov edx, 9
	mov esi, ebp
	add esi, -36
	mov eax, [esi]
	mov eax, edx
	mov esi, ebp
	add esi, -36
	mov [esi], eax
	mov edx, 10
	mov esi, ebp
	add esi, -40
	mov eax, [esi]
	mov eax, edx
	mov esi, ebp
	add esi, -40
	mov [esi], eax
	mov edx, 11
	mov esi, ebp
	add esi, -44
	mov eax, [esi]
	mov eax, edx
	mov esi, ebp
	add esi, -44
	mov [esi], eax
	mov edx, 12
	mov esi, ebp
	add esi, -48
	mov eax, [esi]
	mov eax, edx
	mov esi, ebp
	add esi, -48
	mov [esi], eax
	mov edx, 1
	mov eax, edx
	mov edx, 2
	mov ebx, edx
	mov edx, 3
	mov esi, ebp
	add esi, -52
	mov [esi], eax
	mov esi, ebp
	add esi, -60
	mov eax, [esi]
	mov eax, edx
	mov esi, ebp
	add esi, -60
	mov [esi], eax
	mov esi, ebp
	add esi, -52
	mov eax, [esi]
	mov edx, 4
	mov esi, ebp
	add esi, -52
	mov [esi], eax
	mov esi, ebp
	add esi, -64
	mov eax, [esi]
	mov eax, edx
	mov esi, ebp
	add esi, -64
	mov [esi], eax
	mov esi, ebp
	add esi, -52
	mov eax, [esi]
	mov edx, 5
	mov esi, ebp
	add esi, -52
	mov [esi], eax
	mov esi, ebp
	add esi, -68
	mov eax, [esi]
	mov eax, edx
	mov esi, ebp
	add esi, -68
	mov [esi], eax
	mov esi, ebp
	add esi, -52
	mov eax, [esi]
	mov edx, 6
	mov esi, ebp
	add esi, -52
	mov [esi], eax
	mov esi, ebp
	add esi, -72
	mov eax, [esi]
	mov eax, edx
	mov esi, ebp
	add esi, -72
	mov [esi], eax
	mov esi, ebp
	add esi, -52
	mov eax, [esi]
	mov edx, 7
	mov esi, ebp
	add esi, -52
	mov [esi], eax
	mov esi, ebp
	add esi, -76
	mov eax, [esi]
	mov eax, edx
	mov esi, ebp
	add esi, -76
	mov [esi], eax
	mov esi, ebp
	add esi, -52
	mov eax, [esi]
	mov edx, 8
	mov esi, ebp
	add esi, -52
	mov [esi], eax
	mov esi, ebp
	add esi, -80
	mov eax, [esi]
	mov eax, edx
	mov esi, ebp
	add esi, -80
	mov [esi], eax
	mov esi, ebp
	add esi, -52
	mov eax, [esi]
	mov edx, 9
	mov esi, ebp
	add esi, -52
	mov [esi], eax
	mov esi, ebp
	add esi, -84
	mov eax, [esi]
	mov eax, edx
	mov esi, ebp
	add esi, -84
	mov [esi], eax
	mov esi, ebp
	add esi, -52
	mov eax, [esi]
	mov edx, 10
	mov esi, ebp
	add esi, -52
	mov [esi], eax
	mov esi, ebp
	add esi, -88
	mov eax, [esi]
	mov eax, edx
	mov esi, ebp
	add esi, -88
	mov [esi], eax
	mov esi, ebp
	add esi, -52
	mov eax, [esi]
	mov edx, 11
	mov esi, ebp
	add esi, -52
	mov [esi], eax
	mov esi, ebp
	add esi, -92
	mov eax, [esi]
	mov eax, edx
	mov esi, ebp
	add esi, -92
	mov [esi], eax
	mov esi, ebp
	add esi, -52
	mov eax, [esi]
	mov edx, 12
	mov esi, ebp
	add esi, -52
	mov [esi], eax
	mov esi, ebp
	add esi, -96
	mov eax, [esi]
	mov eax, edx
	mov esi, ebp
	add esi, -96
	mov [esi], eax
	mov esi, ebp
	add esi, -52
	mov eax, [esi]
	mov esi, ebx
	add esi, eax
	mov edx, esi
	mov ecx, edx
	mov esi, ebp
	add esi, -52
	mov [esi], eax
	mov esi, ebp
	add esi, -60
	mov eax, [esi]
	mov esi, eax
	add esi, ecx
	mov edx, esi
	mov esi, ebp
	add esi, -60
	mov [esi], eax
	mov esi, ebp
	add esi, -52
	mov eax, [esi]
	mov ecx, edx
	mov esi, ebp
	add esi, -52
	mov [esi], eax
	mov esi, ebp
	add esi, -64
	mov eax, [esi]
	mov esi, eax
	add esi, ecx
	mov edx, esi
	mov esi, ebp
	add esi, -64
	mov [esi], eax
	mov esi, ebp
	add esi, -52
	mov eax, [esi]
	mov ecx, edx
	mov esi, ebp
	add esi, -52
	mov [esi], eax
	mov esi, ebp
	add esi, -68
	mov eax, [esi]
	mov esi, eax
	add esi, ecx
	mov edx, esi
	mov esi, ebp
	add esi, -68
	mov [esi], eax
	mov esi, ebp
	add esi, -52
	mov eax, [esi]
	mov ecx, edx
	mov esi, ebp
	add esi, -52
	mov [esi], eax
	mov esi, ebp
	add esi, -72
	mov eax, [esi]
	mov esi, eax
	add esi, ecx
	mov edx, esi
	mov esi, ebp
	add esi, -72
	mov [esi], eax
	mov esi, ebp
	add esi, -52
	mov eax, [esi]
	mov ecx, edx
	mov esi, ebp
	add esi, -52
	mov [esi], eax
	mov esi, ebp
	add esi, -76
	mov eax, [esi]
	mov esi, eax
	add esi, ecx
	mov edx, esi
	mov esi, ebp
	add esi, -76
	mov [esi], eax
	mov esi, ebp
	add esi, -52
	mov eax, [esi]
	mov ecx, edx
	mov esi, ebp
	add esi, -52
	mov [esi], eax
	mov esi, ebp
	add esi, -80
	mov eax, [esi]
	mov esi, eax
	add esi, ecx
	mov edx, esi
	mov esi, ebp
	add esi, -80
	mov [esi], eax
	mov esi, ebp
	add esi, -52
	mov eax, [esi]
	mov ecx, edx
	mov esi, ebp
	add esi, -52
	mov [esi], eax
	mov esi, ebp
	add esi, -84
	mov eax, [esi]
	mov esi, eax
	add esi, ecx
	mov edx, esi
	mov esi, ebp
	add esi, -84
	mov [esi], eax
	mov esi, ebp
	add esi, -52
	mov eax, [esi]
	mov ecx, edx
	mov esi, ebp
	add esi, -52
	mov [esi], eax
	mov esi, ebp
	add esi, -88
	mov eax, [esi]
	mov esi, eax
	add esi, ecx
	mov edx, esi
	mov esi, ebp
	add esi, -88
	mov [esi], eax
	mov esi, ebp
	add esi, -52
	mov eax, [esi]
	mov ecx, edx
	mov esi, ebp
	add esi, -52
	mov [esi], eax
	mov esi, ebp
	add esi, -92
	mov eax, [esi]
	mov esi, eax
	add esi, ecx
	mov edx, esi
	mov esi, ebp
	add esi, -92
	mov [esi], eax
	mov esi, ebp
	add esi, -52
	mov eax, [esi]
	mov ecx, edx
	mov esi, ebp
	add esi, -52
	mov [esi], eax
	mov esi, ebp
	add esi, -96
	mov eax, [esi]
	mov esi, eax
	add esi, ecx
	mov edx, esi
	mov esi, ebp
	add esi, -96
	mov [esi], eax
	mov esi, ebp
	add esi, -52
	mov eax, [esi]
	mov ecx, edx
	mov edx, ecx
	mov esi, ebp
	add esi, -100
	mov [esi], edx
	mov esi, ebp
	add esi, -56
	mov [esi], ebx
	push eax
	call Mars_PrintInt
	mov edi, eax
	sub esp, 4
	mov esi, ebp
	add esi, -100
	mov edx, [esi]
	mov esi, ebp
	add esi, -56
	mov ebx, [esi]
	mov esi, ebp
	add esi, -100
	mov [esi], edx
	push ebx
	call Mars_PrintInt
	mov edi, eax
	sub esp, 4
	mov esi, ebp
	add esi, -100
	mov edx, [esi]
	mov esi, ebp
	add esi, -60
	mov eax, [esi]
	mov esi, ebp
	add esi, -100
	mov [esi], edx
	mov esi, ebp
	add esi, -60
	mov [esi], eax
	push eax
	call Mars_PrintInt
	mov edi, eax
	sub esp, 4
	mov esi, ebp
	add esi, -100
	mov edx, [esi]
	mov esi, ebp
	add esi, -60
	mov eax, [esi]
	mov esi, ebp
	add esi, -60
	mov [esi], eax
	mov esi, ebp
	add esi, -64
	mov eax, [esi]
	mov esi, ebp
	add esi, -100
	mov [esi], edx
	mov esi, ebp
	add esi, -64
	mov [esi], eax
	push eax
	call Mars_PrintInt
	mov edi, eax
	sub esp, 4
	mov esi, ebp
	add esi, -100
	mov edx, [esi]
	mov esi, ebp
	add esi, -64
	mov eax, [esi]
	mov esi, ebp
	add esi, -64
	mov [esi], eax
	mov esi, ebp
	add esi, -68
	mov eax, [esi]
	mov esi, ebp
	add esi, -100
	mov [esi], edx
	mov esi, ebp
	add esi, -68
	mov [esi], eax
	push eax
	call Mars_PrintInt
	mov edi, eax
	sub esp, 4
	mov esi, ebp
	add esi, -100
	mov edx, [esi]
	mov esi, ebp
	add esi, -68
	mov eax, [esi]
	mov esi, ebp
	add esi, -68
	mov [esi], eax
	mov esi, ebp
	add esi, -72
	mov eax, [esi]
	mov esi, ebp
	add esi, -100
	mov [esi], edx
	mov esi, ebp
	add esi, -72
	mov [esi], eax
	push eax
	call Mars_PrintInt
	mov edi, eax
	sub esp, 4
	mov esi, ebp
	add esi, -100
	mov edx, [esi]
	mov esi, ebp
	add esi, -72
	mov eax, [esi]
	mov esi, ebp
	add esi, -72
	mov [esi], eax
	mov esi, ebp
	add esi, -76
	mov eax, [esi]
	mov esi, ebp
	add esi, -100
	mov [esi], edx
	mov esi, ebp
	add esi, -76
	mov [esi], eax
	push eax
	call Mars_PrintInt
	mov edi, eax
	sub esp, 4
	mov esi, ebp
	add esi, -100
	mov edx, [esi]
	mov esi, ebp
	add esi, -76
	mov eax, [esi]
	mov esi, ebp
	add esi, -76
	mov [esi], eax
	mov esi, ebp
	add esi, -80
	mov eax, [esi]
	mov esi, ebp
	add esi, -100
	mov [esi], edx
	mov esi, ebp
	add esi, -80
	mov [esi], eax
	push eax
	call Mars_PrintInt
	mov edi, eax
	sub esp, 4
	mov esi, ebp
	add esi, -100
	mov edx, [esi]
	mov esi, ebp
	add esi, -80
	mov eax, [esi]
	mov esi, ebp
	add esi, -80
	mov [esi], eax
	mov esi, ebp
	add esi, -84
	mov eax, [esi]
	mov esi, ebp
	add esi, -100
	mov [esi], edx
	mov esi, ebp
	add esi, -84
	mov [esi], eax
	push eax
	call Mars_PrintInt
	mov edi, eax
	sub esp, 4
	mov esi, ebp
	add esi, -100
	mov edx, [esi]
	mov esi, ebp
	add esi, -84
	mov eax, [esi]
	mov esi, ebp
	add esi, -84
	mov [esi], eax
	mov esi, ebp
	add esi, -88
	mov eax, [esi]
	mov esi, ebp
	add esi, -100
	mov [esi], edx
	mov esi, ebp
	add esi, -88
	mov [esi], eax
	push eax
	call Mars_PrintInt
	mov edi, eax
	sub esp, 4
	mov esi, ebp
	add esi, -100
	mov edx, [esi]
	mov esi, ebp
	add esi, -88
	mov eax, [esi]
	mov esi, ebp
	add esi, -88
	mov [esi], eax
	mov esi, ebp
	add esi, -92
	mov eax, [esi]
	mov esi, ebp
	add esi, -100
	mov [esi], edx
	mov esi, ebp
	add esi, -92
	mov [esi], eax
	push eax
	call Mars_PrintInt
	mov edi, eax
	sub esp, 4
	mov esi, ebp
	add esi, -100
	mov edx, [esi]
	mov esi, ebp
	add esi, -92
	mov eax, [esi]
	mov esi, ebp
	add esi, -92
	mov [esi], eax
	mov esi, ebp
	add esi, -96
	mov eax, [esi]
	mov esi, ebp
	add esi, -100
	mov [esi], edx
	mov esi, ebp
	add esi, -96
	mov [esi], eax
	push eax
	call Mars_PrintInt
	mov edi, eax
	sub esp, 4
	mov esi, ebp
	add esi, -100
	mov edx, [esi]
	mov esi, ebp
	add esi, -96
	mov eax, [esi]
	mov esi, ebp
	add esi, -96
	mov [esi], eax
	push edx
	call Mars_PrintInt
	mov edi, eax
	sub esp, 4
	mov esi, ebp
	add esi, -4
	mov eax, [esi]
	mov esi, ebp
	add esi, -4
	mov [esi], eax
	push eax
	call Mars_PrintInt
	mov edi, eax
	sub esp, 4
	mov esi, ebp
	add esi, -4
	mov eax, [esi]
	mov esi, ebp
	add esi, -4
	mov [esi], eax
	mov esi, ebp
	add esi, -8
	mov eax, [esi]
	mov esi, ebp
	add esi, -8
	mov [esi], eax
	push eax
	call Mars_PrintInt
	mov edi, eax
	sub esp, 4
	mov esi, ebp
	add esi, -8
	mov eax, [esi]
	mov esi, ebp
	add esi, -8
	mov [esi], eax
	mov esi, ebp
	add esi, -12
	mov eax, [esi]
	mov esi, ebp
	add esi, -12
	mov [esi], eax
	push eax
	call Mars_PrintInt
	mov edi, eax
	sub esp, 4
	mov esi, ebp
	add esi, -12
	mov eax, [esi]
	mov esi, ebp
	add esi, -12
	mov [esi], eax
	mov esi, ebp
	add esi, -16
	mov eax, [esi]
	mov esi, ebp
	add esi, -16
	mov [esi], eax
	push eax
	call Mars_PrintInt
	mov edi, eax
	sub esp, 4
	mov esi, ebp
	add esi, -16
	mov eax, [esi]
	mov esi, ebp
	add esi, -16
	mov [esi], eax
	mov esi, ebp
	add esi, -20
	mov eax, [esi]
	mov esi, ebp
	add esi, -20
	mov [esi], eax
	push eax
	call Mars_PrintInt
	mov edi, eax
	sub esp, 4
	mov esi, ebp
	add esi, -20
	mov eax, [esi]
	mov esi, ebp
	add esi, -20
	mov [esi], eax
	mov esi, ebp
	add esi, -24
	mov eax, [esi]
	mov esi, ebp
	add esi, -24
	mov [esi], eax
	push eax
	call Mars_PrintInt
	mov edi, eax
	sub esp, 4
	mov esi, ebp
	add esi, -24
	mov eax, [esi]
	mov esi, ebp
	add esi, -24
	mov [esi], eax
	mov esi, ebp
	add esi, -28
	mov eax, [esi]
	mov esi, ebp
	add esi, -28
	mov [esi], eax
	push eax
	call Mars_PrintInt
	mov edi, eax
	sub esp, 4
	mov esi, ebp
	add esi, -28
	mov eax, [esi]
	mov esi, ebp
	add esi, -28
	mov [esi], eax
	mov esi, ebp
	add esi, -32
	mov eax, [esi]
	mov esi, ebp
	add esi, -32
	mov [esi], eax
	push eax
	call Mars_PrintInt
	mov edi, eax
	sub esp, 4
	mov esi, ebp
	add esi, -32
	mov eax, [esi]
	mov esi, ebp
	add esi, -32
	mov [esi], eax
	mov esi, ebp
	add esi, -36
	mov eax, [esi]
	mov esi, ebp
	add esi, -36
	mov [esi], eax
	push eax
	call Mars_PrintInt
	mov edi, eax
	sub esp, 4
	mov esi, ebp
	add esi, -36
	mov eax, [esi]
	mov esi, ebp
	add esi, -36
	mov [esi], eax
	mov esi, ebp
	add esi, -40
	mov eax, [esi]
	mov esi, ebp
	add esi, -40
	mov [esi], eax
	push eax
	call Mars_PrintInt
	mov edi, eax
	sub esp, 4
	mov esi, ebp
	add esi, -40
	mov eax, [esi]
	mov esi, ebp
	add esi, -40
	mov [esi], eax
	mov esi, ebp
	add esi, -44
	mov eax, [esi]
	mov esi, ebp
	add esi, -44
	mov [esi], eax
	push eax
	call Mars_PrintInt
	mov edi, eax
	sub esp, 4
	mov esi, ebp
	add esi, -44
	mov eax, [esi]
	mov esi, ebp
	add esi, -44
	mov [esi], eax
	mov esi, ebp
	add esi, -48
	mov eax, [esi]
	mov esi, ebp
	add esi, -48
	mov [esi], eax
	push eax
	call Mars_PrintInt
	mov edi, eax
	sub esp, 4
	mov esi, ebp
	add esi, -48
	mov eax, [esi]
	mov esi, ebp
	add esi, -48
	mov [esi], eax
	mov ebx, 0
	mov eax, ebx
	mov esp, ebp
	pop ebp
	ret
end __init
